# Generated by Django 3.2.4 on 2021-06-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=30, null=True)),
                ('JobProfile', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.TextField(blank=True, max_length=200, null=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.master')),
            ],
            options={
                'db_table': 'PersonalInfo',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=3)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.user')),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LangName', models.CharField(max_length=30)),
                ('Level', models.CharField(max_length=3)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.user')),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(auto_created=True)),
                ('JobProfile', models.CharField(max_length=30)),
                ('EndDate', models.DateField(default='2021-06-01')),
                ('IsContinue', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.user')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(auto_created=True)),
                ('Board', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=20)),
                ('EndDate', models.DateField(default='2021-06-01')),
                ('IsContinue', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.user')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
    ]
