# Generated by Django 3.2.4 on 2021-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10),
            preserve_default=False,
        ),
    ]
